=== Vkuzmich96/GeneralTaskRepository/3task/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.epam.com"
            targetNamespace="http://www.epam.com"
            elementFormDefault="qualified"
>
    <xs:element name="candies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candi" type="CandiInfo" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CandiInfo">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:minLength value="20"/>
                        <xs:pattern value="[A-Z][a-z\-]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="energy">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="500"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
            <xs:element name="type">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="filled" type="xs:boolean"/>
                        <xs:element name="typeName" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ingredients" type="IngredientInfo"/>
            <xs:element name="value" type="ValueInfo"/>
            <xs:element name="prodaction" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="IngredientInfo">
        <xs:sequence>
            <xs:element name="woter">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="100"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
            <xs:element name="sugar">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="100"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ValueInfo">
        <xs:sequence>
            <xs:element name="protein">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="100"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
            <xs:element name="fat">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="100"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
            <xs:element name="carbohydrates" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Vkuzmich96/GeneralTaskRepository/3task/src/main/resources/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies
        xmlns="http://www.epam.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.epam.com ./schema.xsd"
>
    <candi id ="0">
        <name>Alyonka</name>
        <energy>100</energy>
        <type>
            <filled>true</filled>
            <typeName>chocolate</typeName>
        </type>
        <ingredients>
            <woter>100</woter>
            <sugar>100</sugar>
        </ingredients>
        <value>
            <protein>50</protein>
            <fat>50</fat>
            <carbohydrates>50</carbohydrates>
        </value>
        <prodaction>Kommunarka</prodaction>
    </candi>
    <candi id ="1">
        <name>Milko</name>
        <energy>100</energy>
        <type>
            <filled>false</filled>
            <typeName>chocolate</typeName>
        </type>
        <ingredients>
            <woter>100</woter>
            <sugar>55</sugar>
        </ingredients>
        <value>
            <protein>51</protein>
            <fat>55</fat>
            <carbohydrates>53</carbohydrates>
        </value>
        <prodaction>Kommunarka</prodaction>
    </candi>
    <candi id ="2">
        <name>Caramel</name>
        <energy>100</energy>
        <type>
            <filled>false</filled>
            <typeName>Caramel</typeName>
        </type>
        <ingredients>
            <woter>100</woter>
            <sugar>55</sugar>
        </ingredients>
        <value>
            <protein>51</protein>
            <fat>55</fat>
            <carbohydrates>53</carbohydrates>
        </value>
        <prodaction>Kommunarka</prodaction>
    </candi>
</candies>
